// lib/screens/settings/faq_screen.dart

import 'package:flutter/material.dart';
import 'dart:ui';

import '../../core/constants/app_colors.dart';
import '../../core/constants/app_constants.dart';
import '../../core/constants/app_text_styles.dart';
import '../../core/theme/app_theme.dart';

class FaqScreen extends StatelessWidget {
  static const String routeName = '/faq';

  const FaqScreen({super.key});

  final List<Map<String, String>> _faqs = const [
    {
      'question': 'How does the AI mock interview work?',
      'answer': 'Our AI uses advanced language models to generate and ask interview questions tailored to your chosen job role and difficulty. It then analyzes your responses based on various metrics like speaking rate, clarity, and filler words to provide a comprehensive report.'
    },
    {
      'question': 'Is my interview data saved privately?',
      'answer': 'Yes, your interview data is stored securely in your private Firestore collection, accessible only by you. You can review your past performance in the History section or delete your account to permanently remove all data.'
    },
    {
      'question': 'How is the feedback generated?',
      'answer': 'The feedback is generated by a powerful AI model that processes your transcribed response and performance metrics. It provides personalized, actionable suggestions to help you improve your interview skills.'
    },
    {
      'question': 'What are the different difficulty levels?',
      'answer': 'The difficulty levels (Easy, Medium, Hard) correspond to the complexity and depth of the questions asked. "Easy" focuses on fundamental concepts, while "Hard" delves into complex, architectural, or situational problems.'
    },
    {
      'question': 'How can I change my profile picture?',
      'answer': 'You can change your profile picture from the "Edit Profile" section, accessible from the main settings screen. Simply tap on your current profile picture and select a new image from your device gallery.'
    },
    {
      'question': 'Can I share my interview reports?',
      'answer': 'Currently, the app keeps your reports private for personal improvement. However, you can manually copy and paste sections of the report to share with mentors or friends if you wish.'
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.backgroundDark,
      appBar: AppBar(
        title: Text(
          'Frequently Asked Questions',
          style: AppTextStyles.heading3.copyWith(color: AppColors.textPrimaryDark),
        ),
        backgroundColor: AppColors.backgroundDark.withOpacity(0.5),
        flexibleSpace: ClipRect(
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
            child: Container(color: Colors.transparent),
          ),
        ),
      ),
      body: Stack(
        children: [
          Positioned.fill(
            child: AnimatedContainer(
              duration: const Duration(seconds: 5),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                  colors: [
                    AppColors.backgroundDark,
                    AppColors.primaryDark.withOpacity(0.8),
                    AppColors.backgroundDark,
                  ],
                  stops: const [0.0, 0.5, 1.0],
                ),
              ),
            ),
          ),
          SingleChildScrollView(
            padding: const EdgeInsets.all(AppConstants.paddingLarge),
            child: AppTheme.applyGlassmorphism(
              blurX: 10.0,
              blurY: 10.0,
              opacity: 0.15,
              child: Padding(
                padding: const EdgeInsets.all(AppConstants.paddingMedium),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: _faqs.map((faq) {
                    return Padding(
                      padding: const EdgeInsets.only(bottom: AppConstants.paddingSmall),
                      child: Theme(
                        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
                        child: ExpansionTile(
                          collapsedIconColor: AppColors.textSecondaryDark,
                          iconColor: AppColors.primaryLight,
                          title: Text(
                            faq['question']!,
                            style: AppTextStyles.bodyLarge.copyWith(color: AppColors.textPrimaryDark, fontWeight: FontWeight.bold),
                          ),
                          children: <Widget>[
                            Padding(
                              padding: const EdgeInsets.symmetric(horizontal: AppConstants.paddingLarge, vertical: AppConstants.paddingSmall),
                              child: Text(
                                faq['answer']!,
                                style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textSecondaryDark),
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  }).toList(),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
