// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq_yF1WjwZIve72aBia8vp0C3sudODHdA',
    appId: '1:494551279960:web:4468ad8abe4f4bd82c9d2d',
    messagingSenderId: '494551279960',
    projectId: 'interviewace-ffd61',
    authDomain: 'interviewace-ffd61.firebaseapp.com',
    databaseURL: 'https://interviewace-ffd61-default-rtdb.firebaseio.com',
    storageBucket: 'interviewace-ffd61.firebasestorage.app',
    measurementId: 'G-XQQZV556M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDaOCAgjR1LTebD3c1H0iC-g22rYurvsA',
    appId: '1:494551279960:android:2c168dddb545320b2c9d2d',
    messagingSenderId: '494551279960',
    projectId: 'interviewace-ffd61',
    databaseURL: 'https://interviewace-ffd61-default-rtdb.firebaseio.com',
    storageBucket: 'interviewace-ffd61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIHfSKt2snc7oi5T_tkZmfYa3O9Hx3Sg',
    appId: '1:494551279960:ios:5c4bfbce809db6562c9d2d',
    messagingSenderId: '494551279960',
    projectId: 'interviewace-ffd61',
    databaseURL: 'https://interviewace-ffd61-default-rtdb.firebaseio.com',
    storageBucket: 'interviewace-ffd61.firebasestorage.app',
    iosBundleId: 'com.example.interviewace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIHfSKt2snc7oi5T_tkZmfYa3O9Hx3Sg',
    appId: '1:494551279960:ios:5c4bfbce809db6562c9d2d',
    messagingSenderId: '494551279960',
    projectId: 'interviewace-ffd61',
    databaseURL: 'https://interviewace-ffd61-default-rtdb.firebaseio.com',
    storageBucket: 'interviewace-ffd61.firebasestorage.app',
    iosBundleId: 'com.example.interviewace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq_yF1WjwZIve72aBia8vp0C3sudODHdA',
    appId: '1:494551279960:web:4805f73abe8e02c32c9d2d',
    messagingSenderId: '494551279960',
    projectId: 'interviewace-ffd61',
    authDomain: 'interviewace-ffd61.firebaseapp.com',
    databaseURL: 'https://interviewace-ffd61-default-rtdb.firebaseio.com',
    storageBucket: 'interviewace-ffd61.firebasestorage.app',
    measurementId: 'G-GG2EV9CEGX',
  );
}
